### ISSUE TITLE
redis读写锁的加锁解锁逻辑

### ISSUE THREAD

**Issue by hawkinggg** [go-locks/distlock#1]
您好，我正在寻找一个go语言的基于redis的分布式互斥锁/读写锁方案，用于生产环境，正好找到了这里

首先我运行了example测试，单点模式的，感觉没啥问题

然后我花了点时间阅读代码逻辑，但是对于redis-driver中读写锁的加解锁逻辑我没有理解到（比如script.go中脚本代码里的各种判断）

因此，我在想能否有更好的文档或者代码注释来帮助理解这些细节但又关键的地方

**Comment by letsfire** [comment]
好吧，这也是我自己业余开发着玩的，还没有精力去整理代码

**Comment by letsfire** [comment]
你可以说说哪儿不明白或者有问题，看看能不能帮助到你

**Comment by hawkinggg** [comment]
好的 麻烦你了  
https://github.com/go-locks/redis-driver/blob/master/script.go

这里的 readLockScript、readUnlockScript、writeLockScript、writeUnlockScript 这四个脚本的逻辑问题

举个例子，按照现在脚本中的逻辑,以读写锁S为例，开始时没有任何进程持有锁S
1. 进程A尝试加一个读锁，加锁成功，持有中，此时 count == 1  
2. 进程B尝试加一个写锁，加锁会失败，此时count == 1-maxreader 
3. 进程B再试加一个读锁 ，此时也会加锁失败了，因为readLockScript要求count>=0
读模式下添加读锁失败了，这里我就没搞明白了

读写锁的意思应该是：写写互斥 读写互斥 读读不互斥 吧

**Comment by letsfire** [comment]
持有读锁A之后，写锁B失败并将count置小于零，之后的读锁C就不在允许进入。等A释放，B允许进入，B完成释放，C才允许进入。如果让读锁不断进入，那写锁就永远没机会了吧。count减去maxreader就是为了给写锁占坑的，告诉后面的读锁先等待。写锁等待已在的读锁完成，后续读锁等待已占坑的写锁完成，所以读写互斥

**Comment by hawkinggg** [comment]
哦,是因为这是非公平锁而又想给写锁一些优先级才这样弄的吗？那我大致可以这样理解吗:
1. count = 0 ;  既不是读模式也不是写模式
2. count = -maxReaders 	; 写模式 (第4种情况释放完读锁也会处于此状态,但模式应该是1的情况-非读非写)
3. count > 0 ; 读模式 具体数字为当前有多少读锁
4. count = (-maxReaders, 0) ; 有写锁请求后的读模式,后续的读锁会被拒绝

**Comment by letsfire** [comment]
基本就是这样子的

1. count = 0 可读可写
2. count > 0 有读锁，没有任何写锁尝试
3. count + maxReaders > 0 有读锁，有写锁尝试并失败了，写锁等待读锁完成释放，此时 count < 0 新的读锁无法进入
4. count + maxReaders = 0 读锁全部完成，写锁重试成功进入，写锁完成后恢复 count = 0 回到 1 的状态

公平锁需要队列状态的维持，没有实现。但是这个机制和是否公平锁无关，只是为了实现读写互斥，写写互斥，读读不互斥

具体可以看一下GO sync.rwmutex的源码，也是类似的计数器规则，只是我理解不到位，写的可能有BUG

**Comment by hawkinggg** [comment]
哦哦 好的 谢谢，我也是最近才开始用golang的，我再多看看源码琢磨琢磨
